class Person:
    def __init__(self, name, age, gender):
        self.name = name
        self.age = age
        self.gender = gender

    def introduce(self):
        print(f"Hi, I'm {self.name}. I am {self.age} years old and i'm a {self.gender} child.")

# Creating an instance of the Person class
myself = Person(name="MWANGI KIGORO", age=27, gender="male")

# Calling the introduce method
myself.introduce()
